version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=buckpal_db
      - POSTGRES_USER=buckpal_user
      - POSTGRES_PASSWORD=buckpal_password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_SETTINGS_MODULE=buckpal_api.settings
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=buckpal_db
      - POSTGRES_USER=buckpal_user
      - POSTGRES_PASSWORD=buckpal_password
    ports:
      - "5432:5432"

volumes:
  postgres_data: 